### ISSUE TITLE
undefined method `name' for #<Cucumber::Ast::Table::Cells> (NoMethodError)

### ISSUE THREAD

**Issue by alexfalkowski** [darrell/cucumber_teamcity#5]
Here is the error:

```ruby
teamcity_formatter.rb:169:in `format_table_row'
teamcity_formatter.rb:84:in `after_table_row'
```

Any ideas why this would be happening. I am using cucumber 1.3.19

**Comment by PositiveAlex** [comment]
Got this issue too. This problem is that this cucumber formatter wants to get name property for table cell, but the cell is not having it. Should check the code closer.

**Comment by PositiveAlex** [comment]
@alexfalkowski 
i have fixed it.

open this file and find method called `format_table_row`

now replace one line of this method to this one:

`%q{%s %10s %-90s @ %s} % [timestamp_short, status, row.name, row.line] unless row[0].line == -1`

The problem was that cucumber retrieves the whole table with headers, so the header row with line == -1 has not `name` field because it's like tecnical row.

**Comment by alexfalkowski** [comment]
Thank you :)

**Comment by darrell** [comment]
We can commit this as an enhancement if you think it worthwhile.

**Comment by PositiveAlex** [comment]
@darrell I'm already made a pull request into your repo. Maybe it's not a pretty-style fix but at least the formatter works with this. You are the one who decide :-)

**Comment by darrell** [comment]
Ahh, OK, merged!
